version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ../test/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
