version: '3'

# Сборка прод-стека из исходников
services:
  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./var/postgresql-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
