name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: lein deps

    - name: cljfmt-check
      run: lein cljfmt check
